# Generated by Django 5.2 on 2025-04-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AberturaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('cc', models.CharField(max_length=20, verbose_name='Centro de Custo')),
                ('cod_cliente', models.IntegerField()),
                ('cod_intervencao', models.IntegerField()),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('A', 'Alta'), ('C', 'Crítica')], max_length=10)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
