# Generated by Django 5.2 on 2025-04-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=20, unique=True)),
                ('nome_cliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoIntervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_intervencao', models.CharField(max_length=20, unique=True)),
                ('descricao_motivo', models.TextField()),
            ],
        ),
    ]
