# Generated by Django 5.2 on 2025-04-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0002_cliente_motivointervencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aberturaos',
            name='cod_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuos.cliente'),
        ),
        migrations.AlterField(
            model_name='aberturaos',
            name='cod_intervencao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuos.motivointervencao'),
        ),
    ]
