# Generated by Django 5.2 on 2025-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0003_alter_aberturaos_cod_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_custo', models.CharField(max_length=10, unique=True)),
                ('descricao_custo', models.CharField(max_length=255)),
            ],
        ),
    ]
