# Generated by Django 5.2 on 2025-07-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0004_centrodecusto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
