# Generated by Django 5.2 on 2025-07-17 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0005_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroInicioOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('numero_os', models.CharField(max_length=20)),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo_dia', models.CharField(blank=True, choices=[('ND', 'Dia Normal (Seg-Sex)'), ('SA', 'Sábado'), ('DF', 'Domingo ou Feriado')], max_length=2)),
            ],
        ),
    ]
