# Generated by Django 5.2.4 on 2025-07-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0007_colaborador_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroinicioos',
            name='hora_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
