# Generated by Django 5.2.4 on 2025-07-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0008_registroinicioos_hora_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='aberturaos',
            name='ssm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SSM'),
        ),
    ]
