# Generated by Django 5.2.4 on 2025-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0009_aberturaos_ssm'),
    ]

    operations = [
        migrations.AddField(
            model_name='aberturaos',
            name='status',
            field=models.CharField(choices=[('Em Aberto', 'Em Aberto'), ('Finalizada', 'Finalizada')], default='Em Aberto', max_length=20),
        ),
    ]
