# Generated by Django 5.2.4 on 2025-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0010_aberturaos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodecusto',
            name='tag',
            field=models.CharField(blank=True, help_text='Tag opcional para o centro de custo', max_length=50, null=True),
        ),
    ]
