# Generated by Django 5.2.4 on 2025-07-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0011_centrodecusto_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrodecusto',
            name='tag',
        ),
    ]
