# Generated by Django 5.2.4 on 2025-07-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0012_remove_centrodecusto_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('abrir_os', 'Pode abrir nova OS'), ('listar_os', 'Pode listar OSs'), ('cadastrar_cliente', 'Pode cadastrar cliente'), ('cadastrar_motivo', 'Pode cadastrar motivo'), ('cadastrar_colaborador', 'Pode cadastrar colaborador'), ('cadastrar_centro_custo', 'Pode cadastrar centro de custos'), ('lancar_os', 'Pode lançar OS'), ('listar_horas', 'Pode listar horas')],
            },
        ),
    ]
