# Generated by Django 5.2.4 on 2025-08-11 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0013_ordemservico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'permissions': [('abrir_os', 'Pode abrir nova OS'), ('listar_os', 'Pode listar OSs'), ('cadastrar_cliente', 'Pode cadastrar cliente'), ('cadastrar_motivo', 'Pode cadastrar motivo'), ('cadastrar_colaborador', 'Pode cadastrar colaborador'), ('cadastrar_centro_custo', 'Pode cadastrar centro de custos'), ('iniciar_os', 'Pode Iniciar OS'), ('lancamento_os', 'Pode lançar OS'), ('listar_horas', 'Pode listar horas')]},
        ),
        migrations.RemoveField(
            model_name='registroinicioos',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='registroinicioos',
            name='numero_os',
        ),
        migrations.AddField(
            model_name='registroinicioos',
            name='abertura_os',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='menuos.aberturaos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroinicioos',
            name='colaborador',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='menuos.colaborador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aberturaos',
            name='prioridade',
            field=models.CharField(choices=[('MaquinaParada', 'Máquina Parada'), ('OperandoDefeito', 'Operando com Defeito'), ('OperandoProgramada', 'Operando Programada'), ('OperandoParadaMelhoria', 'Operando Parada Melhoria'), ('OperandoMelhoria', 'Operando Melhoria'), ('Outros', 'Outros')], max_length=100),
        ),
    ]
