# Generated by Django 5.2.4 on 2025-08-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0015_remove_registroinicioos_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroinicioos',
            name='abertura_os',
        ),
        migrations.RemoveField(
            model_name='registroinicioos',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='registroinicioos',
            name='matricula',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroinicioos',
            name='numero_os',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
