# Generated by Django 5.2.4 on 2025-08-11 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuos', '0016_remove_registroinicioos_abertura_os_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroinicioos',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='registroinicioos',
            name='numero_os',
        ),
        migrations.AddField(
            model_name='registroinicioos',
            name='abertura_os',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='menuos.aberturaos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroinicioos',
            name='colaborador',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='menuos.colaborador'),
            preserve_default=False,
        ),
    ]
